version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: regex
    versions:
    - 1.4.3
    - 1.4.4
    - 1.4.5
  - dependency-name: serde
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: ssh2
    versions:
    - 0.9.0
  - dependency-name: bzip2
    versions:
    - 0.4.1
  - dependency-name: tar
    versions:
    - 0.4.32
